title: "The Blockchain API Blog"
author: "Josh Wolff"
description: "We post mini-tutorials on how to use our API." # This will show up in places like twitter, linkedin, etc, if you share your sites url as a post.

# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
social-network-links:
  rss: false
  email: "info@theblockchainapi.com"
  twitter_username: "_BlockX_"
  github_username: "BL0CK-X"
  #linkedin_username: "company/the-blockchain-api"
  calendly: "josh-wolff-7/blockx-chat"
  youtube: "c/UCtZh22T-0gjNlPi2FWeoRWg"
  telephone: "+1 415 888 4745"
  discord: "https://discord.gg/d49yzrZRAF"
  #facebook_username: username
  #flickr_username: username
  #instagram_username: username
  #pinterest_username: username
  #youtube_username: username
  #googleplus_username: +username

#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################
theme: "minima"

rss: rss

kramdown:
  syntax_highlighter_opts:
    disable: true
    
plugins:
  - jekyll-feed
  - jekyll-sitemap

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other
